#!/bin/sh

set -e

APP_HOME="/partkeepr"
PARAMETERS_FILE="$APP_HOME/app/config/parameters.php"

echo "Updating file ownership..."
find "$APP_HOME" \( ! -user www-data -o ! -group www-data \) -exec chown www-data:www-data {} \;

echo "Generating parameters... "
mkparameters > "$PARAMETERS_FILE"
chown www-data:www-data "$PARAMETERS_FILE"
chmod 644 "$PARAMETERS_FILE"

echo "Cleaning up..."
rm -rf /tmp/*
